### ISSUE TITLE
[Feature]: Handle lost internet connection in feed

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#1519]
### Describe the problem

Raised off the back of https://github.com/pubky/pubky-app/issues/1384#issuecomment-2891429656.

When performing actions to the feed, if my internet connection goes down then posts don't load in the following scenarios:

1. Changing filters (Reach, Sort & Content) loads no posts and shows "Welcome to your feed!"
2. Changing feeds loads no posts and shows "Welcome to your feed!"
3. Scrolling to bottom of feed stops loading posts, and then on connection restore the feed doesn't continue loading if you scroll up and down the the bottom of the feed. Page must be reloaded to continue loading feed whilst scrolling down.

### Describe the solution

We could handle these scenarios better with a different message when posts cannot be loaded, ideally not by reloading the page as this could lose current scroll position.

**Comment by flaviomoceri** [comment]
As a solution for now, the modal will appear instantly as soon as there is no connection and will remove itself instantly as soon as you regain connection.

**Comment by catch-21** [comment]
Tested on 327a03d4516d86d424cc634e06c90b6521ab0133
@flaviomoceri I'm not a fan of the most recent changes because it causes pubky-app to reload too aggressively. Such as when my network dips out out or switches, which is bound to be likely on mobile but can happen on desktop too. For example, when my computer moves from one wifi network to another then my place in the feed and any incomplete new post gets lost. This happens whether I click 'Try again' or not. It would be better to have a long delay to this action, or use a status icon or toast to inform the internet connection it down rather than forcing a reload.

**Comment by flaviomoceri** [comment]
@catch-21 
I agree with you, I implemented a more "kind" method

When you stay on the same page or only change wifi only an alert appears that indicates the network status, but when you change page the modal continues to appear (on twitter it takes you to another separate page)

I fixed the reset of the post when it fails, so as not to lose its content

**Comment by catch-21** [comment]
Tested on 0c8ac6720d9a91c7b913a4c105d4e4a3d07f6d65

Thanks for addressing the aggressive reloading @flaviomoceri. This passive alert is much better.
Although the addition of the "No internet connection" and "Internet connection restored" toast messages, all three of the original issues listed in the issue description are still occurring. In addition, when internet connection is restored the feed can remain with the "Welcome to your feed!" text and without any posts listed.

Is it possible to reload the feed on internet reconnection without losing position if not at the top?  If so, that may sufficiently address points 1 and 2 because the feed would then update itself once reconnected and less disruptive for the user. Regarding point 3, I appreciate this is related to infinite scroll and can be raised as a separate issue.

**Comment by flaviomoceri** [comment]
Try again @catch-21, now the fees should reload when internet is back and meanwhile show a custom UI to aware the user of the situation instead of showing Welcome to your feed

**Comment by catch-21** [comment]
Tested on ae523c3e660076dd9c40deedd5e507e18fa8c923

This works quite well and addresses all three original listed issues. It may still be too aggressive during network dips but hopefully not. I'd like to try it on mobile after deploying to staging. Let's go with it 💪

**Comment by catch-21** [comment]
Verified in [c8925ac](https://github.com/pubky/pubky-app/tree/c8925acae9bd782ab31801805ed9ed33d3ff19ed)
