### ISSUE TITLE
[Bug]: Editing 'website' or 'x' preset links on profile page causes hang on save

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#828]
### Describe the bug

For some reason, attempting to add values for one or both of the preset links (website or x) and saving causes the edit page to hang and not navigate back to the profile page.  Editing anything else or adding new links does not cause the hang.

### Reproduce

1. Go to edit own profile page
2. Add a website or twitter link to one or both of the present link input fields
3. Click Save Profile
4. Observe indefinite spinner of button and never navigates back to profile page
5. Manual refresh proves the links are saved

### Screenshots / Recording

https://github.com/user-attachments/assets/8eb4313a-1d5a-41c9-9f43-6d4996290a61

### Pubky App Version

c7ece62ac4daee5000c76b39d7228fc5220b5cd1

**Comment by flaviomoceri** [comment]
The problem is caused by when you click the "Save profile" button, before being redirected to profile I make sure that the info just entered corresponds to the profile saved on nexus

But when you add a link like https://synonym.to, in nexus it saves https://synonym.to/, so the two profiles would never be the same causing the inifinite waiting

@SHAcollision  is already aware of it and it should be fixed in the next few weeks

**Comment by SHAcollision** [comment]
From https://github.com/pubky/pubky-app-specs/pull/7
```
URLs with an authority component (like https://synonym.to, which has a scheme and a host) are treated as "authority-based URLs". According to the URL specification, an authority-based URL implicitly refers to the root path (/) if no specific path is provided.
Therefore, https://synonym.to was normalized to https://synonym.to/ because it explicitly added the root path.
```
So Nexus will keep running URL sanitization following the standard and future JS `pubky-app-specs` that the client will use will also sanitize in the same way.

> before being redirected to profile I make sure that the info just entered corresponds to the profile saved on nexus

This is clever, but this should not be needed. We can optimistically assume Nexus will sync it and simply update the user profile in cache with the newly submitted data in the profile.json.

**Comment by catch-21** [comment]
Tested on 82747a41e7fb38cfc3260bb9e5f54c028ba63da0
I observe the same problem still. Reopening.

**Comment by catch-21** [comment]
Verified in 2d1cc74a343ef64e64b76c4f8bf9e252189f790d
